#!/usr/bin/env bash

set -e

ROSVERSION=$(rosversion -d)

if [ $ROSVERSION != "indigo" ] && [ $ROSVERSION != "kinetic" ] 
    then
        git clone https://github.com/ros-drivers/pointgrey_camera_driver ../pointgrey_camera_driver

else
    sudo apt-get install -y ros-$ROSVERSION-pointgrey-camera-description 
fi

sudo apt-get install -y ros-$ROSVERSION-robot-localization 
sudo apt-get install -y ros-$ROSVERSION-controller-manager 
sudo apt-get install -y ros-$ROSVERSION-joint-state-controller 
sudo apt-get install -y ros-$ROSVERSION-diff-drive-controller 
sudo apt-get install -y ros-$ROSVERSION-gazebo-ros 
sudo apt-get install -y ros-$ROSVERSION-gazebo-ros-control 
sudo apt-get install -y ros-$ROSVERSION-gazebo-plugins       
sudo apt-get install -y ros-$ROSVERSION-lms1xx 
sudo apt-get install -y ros-$ROSVERSION-roslint 
sudo apt-get install -y ros-$ROSVERSION-amcl 
sudo apt-get install -y ros-$ROSVERSION-gmapping      
sudo apt-get install -y ros-$ROSVERSION-map-server 
sudo apt-get install -y ros-$ROSVERSION-move-base 
sudo apt-get install -y ros-$ROSVERSION-urdf 
sudo apt-get install -y ros-$ROSVERSION-xacro 
sudo apt-get install -y ros-$ROSVERSION-message-runtime 
sudo apt-get install -y ros-$ROSVERSION-topic-tools 
sudo apt-get install -y ros-$ROSVERSION-teleop-twist-joy
sudo apt-get install -y ros-$ROSVERSION-robot-state-publisher
sudo apt-get install -y ros-$ROSVERSION-topic-tools
sudo apt-get install -y ros-$ROSVERSION-image-proc
sudo apt-get install -y ros-$ROSVERSION-lms1xx
sudo apt-get install -y ros-$ROSVERSION-velodyne-*

echo "All dependencies installed!"
